let ENDBOSS_IMAGES;

function endbossLevel1() {
ENDBOSS_IMAGES = {
ENDBOSS_IDLE: [
    'img/endboss/Characters 05/Idle/Idle_00.png',
    'img/endboss/Characters 05/Idle/Idle_01.png',
    'img/endboss/Characters 05/Idle/Idle_02.png',
    'img/endboss/Characters 05/Idle/Idle_03.png',
    'img/endboss/Characters 05/Idle/Idle_04.png',
    'img/endboss/Characters 05/Idle/Idle_05.png',
    'img/endboss/Characters 05/Idle/Idle_06.png',
    'img/endboss/Characters 05/Idle/Idle_07.png',
    'img/endboss/Characters 05/Idle/Idle_08.png',
    'img/endboss/Characters 05/Idle/Idle_09.png',
    'img/endboss/Characters 05/Idle/Idle_10.png',
    'img/endboss/Characters 05/Idle/Idle_11.png',
    'img/endboss/Characters 05/Idle/Idle_12.png',
    'img/endboss/Characters 05/Idle/Idle_13.png',
    'img/endboss/Characters 05/Idle/Idle_14.png',
    'img/endboss/Characters 05/Idle/Idle_15.png',
    'img/endboss/Characters 05/Idle/Idle_16.png',
    'img/endboss/Characters 05/Idle/Idle_17.png',
    'img/endboss/Characters 05/Idle/Idle_18.png',
    'img/endboss/Characters 05/Idle/Idle_19.png',
],

ENDBOSS_WALK: [
    'img/endboss/Characters 05/Walk/Walk_00.png',
    'img/endboss/Characters 05/Walk/Walk_01.png',
    'img/endboss/Characters 05/Walk/Walk_02.png',
    'img/endboss/Characters 05/Walk/Walk_03.png',
    'img/endboss/Characters 05/Walk/Walk_04.png',
    'img/endboss/Characters 05/Walk/Walk_05.png',
    'img/endboss/Characters 05/Walk/Walk_06.png',
    'img/endboss/Characters 05/Walk/Walk_07.png',
    'img/endboss/Characters 05/Walk/Walk_08.png',
    'img/endboss/Characters 05/Walk/Walk_09.png',
    'img/endboss/Characters 05/Walk/Walk_10.png',
    'img/endboss/Characters 05/Walk/Walk_11.png',
    'img/endboss/Characters 05/Walk/Walk_12.png',
    'img/endboss/Characters 05/Walk/Walk_13.png',
    'img/endboss/Characters 05/Walk/Walk_14.png',
    'img/endboss/Characters 05/Walk/Walk_15.png',
    'img/endboss/Characters 05/Walk/Walk_16.png',
    'img/endboss/Characters 05/Walk/Walk_17.png',
    'img/endboss/Characters 05/Walk/Walk_18.png',
    'img/endboss/Characters 05/Walk/Walk_19.png',
],

ENDBOSS_ATTACK: [
    'img/endboss/Characters 05/Attack/Attack_00.png',
    'img/endboss/Characters 05/Attack/Attack_01.png',
    'img/endboss/Characters 05/Attack/Attack_02.png',
    'img/endboss/Characters 05/Attack/Attack_03.png',
    'img/endboss/Characters 05/Attack/Attack_04.png',
    'img/endboss/Characters 05/Attack/Attack_05.png',
    'img/endboss/Characters 05/Attack/Attack_06.png',
    'img/endboss/Characters 05/Attack/Attack_07.png',
    'img/endboss/Characters 05/Attack/Attack_08.png',
    'img/endboss/Characters 05/Attack/Attack_09.png',
    'img/endboss/Characters 05/Attack/Attack_10.png',
    'img/endboss/Characters 05/Attack/Attack_11.png',
    'img/endboss/Characters 05/Attack/Attack_12.png',
    'img/endboss/Characters 05/Attack/Attack_13.png',
    'img/endboss/Characters 05/Attack/Attack_14.png',
    'img/endboss/Characters 05/Attack/Attack_15.png',
    'img/endboss/Characters 05/Attack/Attack_16.png',
    'img/endboss/Characters 05/Attack/Attack_17.png',
    'img/endboss/Characters 05/Attack/Attack_18.png',
    'img/endboss/Characters 05/Attack/Attack_19.png',
    'img/endboss/Characters 05/Attack/Attack_20.png',
    'img/endboss/Characters 05/Attack/Attack_21.png',
    'img/endboss/Characters 05/Attack/Attack_22.png',
    'img/endboss/Characters 05/Attack/Attack_23.png',
    'img/endboss/Characters 05/Attack/Attack_24.png',
],

ENDBOSS_HURT: [
    'img/endboss/Characters 05/Get Hit/Get Hit_00.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_01.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_02.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_03.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_04.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_05.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_06.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_07.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_08.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_09.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_10.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_11.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_12.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_13.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_14.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_15.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_16.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_17.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_18.png',
    'img/endboss/Characters 05/Get Hit/Get Hit_19.png',
],

ENDBOSS_DEAD: [
    'img/endboss/Characters 05/Death/Death_00.png',
    'img/endboss/Characters 05/Death/Death_01.png',
    'img/endboss/Characters 05/Death/Death_02.png',
    'img/endboss/Characters 05/Death/Death_03.png',
    'img/endboss/Characters 05/Death/Death_04.png',
    'img/endboss/Characters 05/Death/Death_05.png',
    'img/endboss/Characters 05/Death/Death_06.png',
    'img/endboss/Characters 05/Death/Death_07.png',
    'img/endboss/Characters 05/Death/Death_08.png',
    'img/endboss/Characters 05/Death/Death_09.png',
    'img/endboss/Characters 05/Death/Death_10.png',
    'img/endboss/Characters 05/Death/Death_11.png',
    'img/endboss/Characters 05/Death/Death_12.png',
    'img/endboss/Characters 05/Death/Death_13.png',
    'img/endboss/Characters 05/Death/Death_14.png',
    'img/endboss/Characters 05/Death/Death_15.png',
    'img/endboss/Characters 05/Death/Death_16.png',
    'img/endboss/Characters 05/Death/Death_17.png',
    'img/endboss/Characters 05/Death/Death_18.png',
    'img/endboss/Characters 05/Death/Death_19.png',
    'img/endboss/Characters 05/Death/Death_20.png',
    'img/endboss/Characters 05/Death/Death_21.png',
    'img/endboss/Characters 05/Death/Death_22.png',
    'img/endboss/Characters 05/Death/Death_23.png',
    'img/endboss/Characters 05/Death/Death_24.png',
    'img/endboss/Characters 05/Death/Death_25.png',
    'img/endboss/Characters 05/Death/Death_26.png',
    'img/endboss/Characters 05/Death/Death_27.png',
    'img/endboss/Characters 05/Death/Death_28.png',
    'img/endboss/Characters 05/Death/Death_29.png',
    'img/endboss/Characters 05/Death/Death_30.png',
    'img/endboss/Characters 05/Death/Death_31.png',
    'img/endboss/Characters 05/Death/Death_32.png',
    'img/endboss/Characters 05/Death/Death_33.png',
    'img/endboss/Characters 05/Death/Death_34.png',
    'img/endboss/Characters 05/Death/Death_35.png',
    'img/endboss/Characters 05/Death/Death_36.png',
    'img/endboss/Characters 05/Death/Death_37.png',
    'img/endboss/Characters 05/Death/Death_38.png',
    'img/endboss/Characters 05/Death/Death_39.png',
    'img/endboss/Characters 05/Death/Death_40.png',
    'img/endboss/Characters 05/Death/Death_41.png',
    'img/endboss/Characters 05/Death/Death_42.png',
    'img/endboss/Characters 05/Death/Death_43.png',
    'img/endboss/Characters 05/Death/Death_44.png',
]

}
}

function endbossLevel2() {
    ENDBOSS_IMAGES = {
    ENDBOSS_IDLE: [
        'img/allEndboss/Characters/Characters 11/Idle/Idle_00.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_01.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_02.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_03.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_04.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_05.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_06.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_07.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_08.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_09.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_10.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_11.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_12.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_13.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_14.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_15.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_16.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_17.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_18.png',
        'img/allEndboss/Characters/Characters 11/Idle/Idle_19.png',
    ],
    
    ENDBOSS_WALK: [
        'img/allEndboss/Characters/Characters 11/Walk/Walk_00.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_01.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_02.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_03.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_04.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_05.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_06.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_07.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_08.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_09.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_10.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_11.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_12.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_13.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_14.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_15.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_16.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_17.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_18.png',
        'img/allEndboss/Characters/Characters 11/Walk/Walk_19.png',

    ],
    
    ENDBOSS_ATTACK: [
        'img/allEndboss/Characters/Characters 11/Attack/Attack_00.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_01.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_02.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_03.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_04.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_05.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_06.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_07.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_08.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_09.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_10.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_11.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_12.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_13.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_14.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_15.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_16.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_17.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_18.png',
        'img/allEndboss/Characters/Characters 11/Attack/Attack_19.png',
    ],
    
    ENDBOSS_HURT: [
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_00.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_01.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_02.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_03.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_04.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_05.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_06.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_07.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_08.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_09.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_10.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_11.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_12.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_13.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_14.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_15.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_16.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_17.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_18.png',
        'img/allEndboss/Characters/Characters 11/Get Hit/GetHited_19.png',
    ],
    
    ENDBOSS_DEAD: [
        'img/allEndboss/Characters/Characters 11/Death/Death_00.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_01.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_02.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_03.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_04.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_05.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_06.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_07.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_08.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_09.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_10.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_11.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_12.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_13.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_14.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_15.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_16.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_17.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_18.png',
        'img/allEndboss/Characters/Characters 11/Death/Death_19.png',
    ]
    
    }
    }

    function endbossLevel3() {
        ENDBOSS_IMAGES = {
        ENDBOSS_IDLE: [
            'img/endboss/Characters 05/Idle/Idle_00.png',
            'img/endboss/Characters 05/Idle/Idle_01.png',
            'img/endboss/Characters 05/Idle/Idle_02.png',
            'img/endboss/Characters 05/Idle/Idle_03.png',
            'img/endboss/Characters 05/Idle/Idle_04.png',
            'img/endboss/Characters 05/Idle/Idle_05.png',
            'img/endboss/Characters 05/Idle/Idle_06.png',
            'img/endboss/Characters 05/Idle/Idle_07.png',
            'img/endboss/Characters 05/Idle/Idle_08.png',
            'img/endboss/Characters 05/Idle/Idle_09.png',
            'img/endboss/Characters 05/Idle/Idle_10.png',
            'img/endboss/Characters 05/Idle/Idle_11.png',
            'img/endboss/Characters 05/Idle/Idle_12.png',
            'img/endboss/Characters 05/Idle/Idle_13.png',
            'img/endboss/Characters 05/Idle/Idle_14.png',
            'img/endboss/Characters 05/Idle/Idle_15.png',
            'img/endboss/Characters 05/Idle/Idle_16.png',
            'img/endboss/Characters 05/Idle/Idle_17.png',
            'img/endboss/Characters 05/Idle/Idle_18.png',
            'img/endboss/Characters 05/Idle/Idle_19.png',
        ],
        
        ENDBOSS_WALK: [
            'img/endboss/Characters 05/Walk/Walk_00.png',
            'img/endboss/Characters 05/Walk/Walk_01.png',
            'img/endboss/Characters 05/Walk/Walk_02.png',
            'img/endboss/Characters 05/Walk/Walk_03.png',
            'img/endboss/Characters 05/Walk/Walk_04.png',
            'img/endboss/Characters 05/Walk/Walk_05.png',
            'img/endboss/Characters 05/Walk/Walk_06.png',
            'img/endboss/Characters 05/Walk/Walk_07.png',
            'img/endboss/Characters 05/Walk/Walk_08.png',
            'img/endboss/Characters 05/Walk/Walk_09.png',
            'img/endboss/Characters 05/Walk/Walk_10.png',
            'img/endboss/Characters 05/Walk/Walk_11.png',
            'img/endboss/Characters 05/Walk/Walk_12.png',
            'img/endboss/Characters 05/Walk/Walk_13.png',
            'img/endboss/Characters 05/Walk/Walk_14.png',
            'img/endboss/Characters 05/Walk/Walk_15.png',
            'img/endboss/Characters 05/Walk/Walk_16.png',
            'img/endboss/Characters 05/Walk/Walk_17.png',
            'img/endboss/Characters 05/Walk/Walk_18.png',
            'img/endboss/Characters 05/Walk/Walk_19.png',
        ],
        
        ENDBOSS_ATTACK: [
            'img/endboss/Characters 05/Attack/Attack_00.png',
            'img/endboss/Characters 05/Attack/Attack_01.png',
            'img/endboss/Characters 05/Attack/Attack_02.png',
            'img/endboss/Characters 05/Attack/Attack_03.png',
            'img/endboss/Characters 05/Attack/Attack_04.png',
            'img/endboss/Characters 05/Attack/Attack_05.png',
            'img/endboss/Characters 05/Attack/Attack_06.png',
            'img/endboss/Characters 05/Attack/Attack_07.png',
            'img/endboss/Characters 05/Attack/Attack_08.png',
            'img/endboss/Characters 05/Attack/Attack_09.png',
            'img/endboss/Characters 05/Attack/Attack_10.png',
            'img/endboss/Characters 05/Attack/Attack_11.png',
            'img/endboss/Characters 05/Attack/Attack_12.png',
            'img/endboss/Characters 05/Attack/Attack_13.png',
            'img/endboss/Characters 05/Attack/Attack_14.png',
            'img/endboss/Characters 05/Attack/Attack_15.png',
            'img/endboss/Characters 05/Attack/Attack_16.png',
            'img/endboss/Characters 05/Attack/Attack_17.png',
            'img/endboss/Characters 05/Attack/Attack_18.png',
            'img/endboss/Characters 05/Attack/Attack_19.png',
            'img/endboss/Characters 05/Attack/Attack_20.png',
            'img/endboss/Characters 05/Attack/Attack_21.png',
            'img/endboss/Characters 05/Attack/Attack_22.png',
            'img/endboss/Characters 05/Attack/Attack_23.png',
            'img/endboss/Characters 05/Attack/Attack_24.png',
        ],
        
        ENDBOSS_HURT: [
            'img/endboss/Characters 05/Get Hit/Get Hit_00.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_01.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_02.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_03.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_04.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_05.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_06.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_07.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_08.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_09.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_10.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_11.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_12.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_13.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_14.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_15.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_16.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_17.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_18.png',
            'img/endboss/Characters 05/Get Hit/Get Hit_19.png',
        ],
        
        ENDBOSS_DEAD: [
            'img/endboss/Characters 05/Death/Death_00.png',
            'img/endboss/Characters 05/Death/Death_01.png',
            'img/endboss/Characters 05/Death/Death_02.png',
            'img/endboss/Characters 05/Death/Death_03.png',
            'img/endboss/Characters 05/Death/Death_04.png',
            'img/endboss/Characters 05/Death/Death_05.png',
            'img/endboss/Characters 05/Death/Death_06.png',
            'img/endboss/Characters 05/Death/Death_07.png',
            'img/endboss/Characters 05/Death/Death_08.png',
            'img/endboss/Characters 05/Death/Death_09.png',
            'img/endboss/Characters 05/Death/Death_10.png',
            'img/endboss/Characters 05/Death/Death_11.png',
            'img/endboss/Characters 05/Death/Death_12.png',
            'img/endboss/Characters 05/Death/Death_13.png',
            'img/endboss/Characters 05/Death/Death_14.png',
            'img/endboss/Characters 05/Death/Death_15.png',
            'img/endboss/Characters 05/Death/Death_16.png',
            'img/endboss/Characters 05/Death/Death_17.png',
            'img/endboss/Characters 05/Death/Death_18.png',
            'img/endboss/Characters 05/Death/Death_19.png',
            'img/endboss/Characters 05/Death/Death_20.png',
            'img/endboss/Characters 05/Death/Death_21.png',
            'img/endboss/Characters 05/Death/Death_22.png',
            'img/endboss/Characters 05/Death/Death_23.png',
            'img/endboss/Characters 05/Death/Death_24.png',
            'img/endboss/Characters 05/Death/Death_25.png',
            'img/endboss/Characters 05/Death/Death_26.png',
            'img/endboss/Characters 05/Death/Death_27.png',
            'img/endboss/Characters 05/Death/Death_28.png',
            'img/endboss/Characters 05/Death/Death_29.png',
            'img/endboss/Characters 05/Death/Death_30.png',
            'img/endboss/Characters 05/Death/Death_31.png',
            'img/endboss/Characters 05/Death/Death_32.png',
            'img/endboss/Characters 05/Death/Death_33.png',
            'img/endboss/Characters 05/Death/Death_34.png',
            'img/endboss/Characters 05/Death/Death_35.png',
            'img/endboss/Characters 05/Death/Death_36.png',
            'img/endboss/Characters 05/Death/Death_37.png',
            'img/endboss/Characters 05/Death/Death_38.png',
            'img/endboss/Characters 05/Death/Death_39.png',
            'img/endboss/Characters 05/Death/Death_40.png',
            'img/endboss/Characters 05/Death/Death_41.png',
            'img/endboss/Characters 05/Death/Death_42.png',
            'img/endboss/Characters 05/Death/Death_43.png',
            'img/endboss/Characters 05/Death/Death_44.png',
        ]
        
        }
        }
    
        function endbossLevel4() {
            ENDBOSS_IMAGES = {
            ENDBOSS_IDLE: [
                'img/endboss/Characters 05/Idle/Idle_00.png',
                'img/endboss/Characters 05/Idle/Idle_01.png',
                'img/endboss/Characters 05/Idle/Idle_02.png',
                'img/endboss/Characters 05/Idle/Idle_03.png',
                'img/endboss/Characters 05/Idle/Idle_04.png',
                'img/endboss/Characters 05/Idle/Idle_05.png',
                'img/endboss/Characters 05/Idle/Idle_06.png',
                'img/endboss/Characters 05/Idle/Idle_07.png',
                'img/endboss/Characters 05/Idle/Idle_08.png',
                'img/endboss/Characters 05/Idle/Idle_09.png',
                'img/endboss/Characters 05/Idle/Idle_10.png',
                'img/endboss/Characters 05/Idle/Idle_11.png',
                'img/endboss/Characters 05/Idle/Idle_12.png',
                'img/endboss/Characters 05/Idle/Idle_13.png',
                'img/endboss/Characters 05/Idle/Idle_14.png',
                'img/endboss/Characters 05/Idle/Idle_15.png',
                'img/endboss/Characters 05/Idle/Idle_16.png',
                'img/endboss/Characters 05/Idle/Idle_17.png',
                'img/endboss/Characters 05/Idle/Idle_18.png',
                'img/endboss/Characters 05/Idle/Idle_19.png',
            ],
            
            ENDBOSS_WALK: [
                'img/endboss/Characters 05/Walk/Walk_00.png',
                'img/endboss/Characters 05/Walk/Walk_01.png',
                'img/endboss/Characters 05/Walk/Walk_02.png',
                'img/endboss/Characters 05/Walk/Walk_03.png',
                'img/endboss/Characters 05/Walk/Walk_04.png',
                'img/endboss/Characters 05/Walk/Walk_05.png',
                'img/endboss/Characters 05/Walk/Walk_06.png',
                'img/endboss/Characters 05/Walk/Walk_07.png',
                'img/endboss/Characters 05/Walk/Walk_08.png',
                'img/endboss/Characters 05/Walk/Walk_09.png',
                'img/endboss/Characters 05/Walk/Walk_10.png',
                'img/endboss/Characters 05/Walk/Walk_11.png',
                'img/endboss/Characters 05/Walk/Walk_12.png',
                'img/endboss/Characters 05/Walk/Walk_13.png',
                'img/endboss/Characters 05/Walk/Walk_14.png',
                'img/endboss/Characters 05/Walk/Walk_15.png',
                'img/endboss/Characters 05/Walk/Walk_16.png',
                'img/endboss/Characters 05/Walk/Walk_17.png',
                'img/endboss/Characters 05/Walk/Walk_18.png',
                'img/endboss/Characters 05/Walk/Walk_19.png',
            ],
            
            ENDBOSS_ATTACK: [
                'img/endboss/Characters 05/Attack/Attack_00.png',
                'img/endboss/Characters 05/Attack/Attack_01.png',
                'img/endboss/Characters 05/Attack/Attack_02.png',
                'img/endboss/Characters 05/Attack/Attack_03.png',
                'img/endboss/Characters 05/Attack/Attack_04.png',
                'img/endboss/Characters 05/Attack/Attack_05.png',
                'img/endboss/Characters 05/Attack/Attack_06.png',
                'img/endboss/Characters 05/Attack/Attack_07.png',
                'img/endboss/Characters 05/Attack/Attack_08.png',
                'img/endboss/Characters 05/Attack/Attack_09.png',
                'img/endboss/Characters 05/Attack/Attack_10.png',
                'img/endboss/Characters 05/Attack/Attack_11.png',
                'img/endboss/Characters 05/Attack/Attack_12.png',
                'img/endboss/Characters 05/Attack/Attack_13.png',
                'img/endboss/Characters 05/Attack/Attack_14.png',
                'img/endboss/Characters 05/Attack/Attack_15.png',
                'img/endboss/Characters 05/Attack/Attack_16.png',
                'img/endboss/Characters 05/Attack/Attack_17.png',
                'img/endboss/Characters 05/Attack/Attack_18.png',
                'img/endboss/Characters 05/Attack/Attack_19.png',
                'img/endboss/Characters 05/Attack/Attack_20.png',
                'img/endboss/Characters 05/Attack/Attack_21.png',
                'img/endboss/Characters 05/Attack/Attack_22.png',
                'img/endboss/Characters 05/Attack/Attack_23.png',
                'img/endboss/Characters 05/Attack/Attack_24.png',
            ],
            
            ENDBOSS_HURT: [
                'img/endboss/Characters 05/Get Hit/Get Hit_00.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_01.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_02.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_03.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_04.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_05.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_06.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_07.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_08.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_09.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_10.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_11.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_12.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_13.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_14.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_15.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_16.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_17.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_18.png',
                'img/endboss/Characters 05/Get Hit/Get Hit_19.png',
            ],
            
            ENDBOSS_DEAD: [
                'img/endboss/Characters 05/Death/Death_00.png',
                'img/endboss/Characters 05/Death/Death_01.png',
                'img/endboss/Characters 05/Death/Death_02.png',
                'img/endboss/Characters 05/Death/Death_03.png',
                'img/endboss/Characters 05/Death/Death_04.png',
                'img/endboss/Characters 05/Death/Death_05.png',
                'img/endboss/Characters 05/Death/Death_06.png',
                'img/endboss/Characters 05/Death/Death_07.png',
                'img/endboss/Characters 05/Death/Death_08.png',
                'img/endboss/Characters 05/Death/Death_09.png',
                'img/endboss/Characters 05/Death/Death_10.png',
                'img/endboss/Characters 05/Death/Death_11.png',
                'img/endboss/Characters 05/Death/Death_12.png',
                'img/endboss/Characters 05/Death/Death_13.png',
                'img/endboss/Characters 05/Death/Death_14.png',
                'img/endboss/Characters 05/Death/Death_15.png',
                'img/endboss/Characters 05/Death/Death_16.png',
                'img/endboss/Characters 05/Death/Death_17.png',
                'img/endboss/Characters 05/Death/Death_18.png',
                'img/endboss/Characters 05/Death/Death_19.png',
                'img/endboss/Characters 05/Death/Death_20.png',
                'img/endboss/Characters 05/Death/Death_21.png',
                'img/endboss/Characters 05/Death/Death_22.png',
                'img/endboss/Characters 05/Death/Death_23.png',
                'img/endboss/Characters 05/Death/Death_24.png',
                'img/endboss/Characters 05/Death/Death_25.png',
                'img/endboss/Characters 05/Death/Death_26.png',
                'img/endboss/Characters 05/Death/Death_27.png',
                'img/endboss/Characters 05/Death/Death_28.png',
                'img/endboss/Characters 05/Death/Death_29.png',
                'img/endboss/Characters 05/Death/Death_30.png',
                'img/endboss/Characters 05/Death/Death_31.png',
                'img/endboss/Characters 05/Death/Death_32.png',
                'img/endboss/Characters 05/Death/Death_33.png',
                'img/endboss/Characters 05/Death/Death_34.png',
                'img/endboss/Characters 05/Death/Death_35.png',
                'img/endboss/Characters 05/Death/Death_36.png',
                'img/endboss/Characters 05/Death/Death_37.png',
                'img/endboss/Characters 05/Death/Death_38.png',
                'img/endboss/Characters 05/Death/Death_39.png',
                'img/endboss/Characters 05/Death/Death_40.png',
                'img/endboss/Characters 05/Death/Death_41.png',
                'img/endboss/Characters 05/Death/Death_42.png',
                'img/endboss/Characters 05/Death/Death_43.png',
                'img/endboss/Characters 05/Death/Death_44.png',
            ]
            
            }
            }

            function endbossLevel5() {
                ENDBOSS_IMAGES = {
                ENDBOSS_IDLE: [
                    'img/endboss/Characters 05/Idle/Idle_00.png',
                    'img/endboss/Characters 05/Idle/Idle_01.png',
                    'img/endboss/Characters 05/Idle/Idle_02.png',
                    'img/endboss/Characters 05/Idle/Idle_03.png',
                    'img/endboss/Characters 05/Idle/Idle_04.png',
                    'img/endboss/Characters 05/Idle/Idle_05.png',
                    'img/endboss/Characters 05/Idle/Idle_06.png',
                    'img/endboss/Characters 05/Idle/Idle_07.png',
                    'img/endboss/Characters 05/Idle/Idle_08.png',
                    'img/endboss/Characters 05/Idle/Idle_09.png',
                    'img/endboss/Characters 05/Idle/Idle_10.png',
                    'img/endboss/Characters 05/Idle/Idle_11.png',
                    'img/endboss/Characters 05/Idle/Idle_12.png',
                    'img/endboss/Characters 05/Idle/Idle_13.png',
                    'img/endboss/Characters 05/Idle/Idle_14.png',
                    'img/endboss/Characters 05/Idle/Idle_15.png',
                    'img/endboss/Characters 05/Idle/Idle_16.png',
                    'img/endboss/Characters 05/Idle/Idle_17.png',
                    'img/endboss/Characters 05/Idle/Idle_18.png',
                    'img/endboss/Characters 05/Idle/Idle_19.png',
                ],
                
                ENDBOSS_WALK: [
                    'img/endboss/Characters 05/Walk/Walk_00.png',
                    'img/endboss/Characters 05/Walk/Walk_01.png',
                    'img/endboss/Characters 05/Walk/Walk_02.png',
                    'img/endboss/Characters 05/Walk/Walk_03.png',
                    'img/endboss/Characters 05/Walk/Walk_04.png',
                    'img/endboss/Characters 05/Walk/Walk_05.png',
                    'img/endboss/Characters 05/Walk/Walk_06.png',
                    'img/endboss/Characters 05/Walk/Walk_07.png',
                    'img/endboss/Characters 05/Walk/Walk_08.png',
                    'img/endboss/Characters 05/Walk/Walk_09.png',
                    'img/endboss/Characters 05/Walk/Walk_10.png',
                    'img/endboss/Characters 05/Walk/Walk_11.png',
                    'img/endboss/Characters 05/Walk/Walk_12.png',
                    'img/endboss/Characters 05/Walk/Walk_13.png',
                    'img/endboss/Characters 05/Walk/Walk_14.png',
                    'img/endboss/Characters 05/Walk/Walk_15.png',
                    'img/endboss/Characters 05/Walk/Walk_16.png',
                    'img/endboss/Characters 05/Walk/Walk_17.png',
                    'img/endboss/Characters 05/Walk/Walk_18.png',
                    'img/endboss/Characters 05/Walk/Walk_19.png',
                ],
                
                ENDBOSS_ATTACK: [
                    'img/endboss/Characters 05/Attack/Attack_00.png',
                    'img/endboss/Characters 05/Attack/Attack_01.png',
                    'img/endboss/Characters 05/Attack/Attack_02.png',
                    'img/endboss/Characters 05/Attack/Attack_03.png',
                    'img/endboss/Characters 05/Attack/Attack_04.png',
                    'img/endboss/Characters 05/Attack/Attack_05.png',
                    'img/endboss/Characters 05/Attack/Attack_06.png',
                    'img/endboss/Characters 05/Attack/Attack_07.png',
                    'img/endboss/Characters 05/Attack/Attack_08.png',
                    'img/endboss/Characters 05/Attack/Attack_09.png',
                    'img/endboss/Characters 05/Attack/Attack_10.png',
                    'img/endboss/Characters 05/Attack/Attack_11.png',
                    'img/endboss/Characters 05/Attack/Attack_12.png',
                    'img/endboss/Characters 05/Attack/Attack_13.png',
                    'img/endboss/Characters 05/Attack/Attack_14.png',
                    'img/endboss/Characters 05/Attack/Attack_15.png',
                    'img/endboss/Characters 05/Attack/Attack_16.png',
                    'img/endboss/Characters 05/Attack/Attack_17.png',
                    'img/endboss/Characters 05/Attack/Attack_18.png',
                    'img/endboss/Characters 05/Attack/Attack_19.png',
                    'img/endboss/Characters 05/Attack/Attack_20.png',
                    'img/endboss/Characters 05/Attack/Attack_21.png',
                    'img/endboss/Characters 05/Attack/Attack_22.png',
                    'img/endboss/Characters 05/Attack/Attack_23.png',
                    'img/endboss/Characters 05/Attack/Attack_24.png',
                ],
                
                ENDBOSS_HURT: [
                    'img/endboss/Characters 05/Get Hit/Get Hit_00.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_01.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_02.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_03.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_04.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_05.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_06.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_07.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_08.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_09.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_10.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_11.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_12.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_13.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_14.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_15.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_16.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_17.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_18.png',
                    'img/endboss/Characters 05/Get Hit/Get Hit_19.png',
                ],
                
                ENDBOSS_DEAD: [
                    'img/endboss/Characters 05/Death/Death_00.png',
                    'img/endboss/Characters 05/Death/Death_01.png',
                    'img/endboss/Characters 05/Death/Death_02.png',
                    'img/endboss/Characters 05/Death/Death_03.png',
                    'img/endboss/Characters 05/Death/Death_04.png',
                    'img/endboss/Characters 05/Death/Death_05.png',
                    'img/endboss/Characters 05/Death/Death_06.png',
                    'img/endboss/Characters 05/Death/Death_07.png',
                    'img/endboss/Characters 05/Death/Death_08.png',
                    'img/endboss/Characters 05/Death/Death_09.png',
                    'img/endboss/Characters 05/Death/Death_10.png',
                    'img/endboss/Characters 05/Death/Death_11.png',
                    'img/endboss/Characters 05/Death/Death_12.png',
                    'img/endboss/Characters 05/Death/Death_13.png',
                    'img/endboss/Characters 05/Death/Death_14.png',
                    'img/endboss/Characters 05/Death/Death_15.png',
                    'img/endboss/Characters 05/Death/Death_16.png',
                    'img/endboss/Characters 05/Death/Death_17.png',
                    'img/endboss/Characters 05/Death/Death_18.png',
                    'img/endboss/Characters 05/Death/Death_19.png',
                    'img/endboss/Characters 05/Death/Death_20.png',
                    'img/endboss/Characters 05/Death/Death_21.png',
                    'img/endboss/Characters 05/Death/Death_22.png',
                    'img/endboss/Characters 05/Death/Death_23.png',
                    'img/endboss/Characters 05/Death/Death_24.png',
                    'img/endboss/Characters 05/Death/Death_25.png',
                    'img/endboss/Characters 05/Death/Death_26.png',
                    'img/endboss/Characters 05/Death/Death_27.png',
                    'img/endboss/Characters 05/Death/Death_28.png',
                    'img/endboss/Characters 05/Death/Death_29.png',
                    'img/endboss/Characters 05/Death/Death_30.png',
                    'img/endboss/Characters 05/Death/Death_31.png',
                    'img/endboss/Characters 05/Death/Death_32.png',
                    'img/endboss/Characters 05/Death/Death_33.png',
                    'img/endboss/Characters 05/Death/Death_34.png',
                    'img/endboss/Characters 05/Death/Death_35.png',
                    'img/endboss/Characters 05/Death/Death_36.png',
                    'img/endboss/Characters 05/Death/Death_37.png',
                    'img/endboss/Characters 05/Death/Death_38.png',
                    'img/endboss/Characters 05/Death/Death_39.png',
                    'img/endboss/Characters 05/Death/Death_40.png',
                    'img/endboss/Characters 05/Death/Death_41.png',
                    'img/endboss/Characters 05/Death/Death_42.png',
                    'img/endboss/Characters 05/Death/Death_43.png',
                    'img/endboss/Characters 05/Death/Death_44.png',
                ]
                
                }
                }

                function endbossLevel6() {
                    ENDBOSS_IMAGES = {
                    ENDBOSS_IDLE: [
                        'img/endboss/Characters 05/Idle/Idle_00.png',
                        'img/endboss/Characters 05/Idle/Idle_01.png',
                        'img/endboss/Characters 05/Idle/Idle_02.png',
                        'img/endboss/Characters 05/Idle/Idle_03.png',
                        'img/endboss/Characters 05/Idle/Idle_04.png',
                        'img/endboss/Characters 05/Idle/Idle_05.png',
                        'img/endboss/Characters 05/Idle/Idle_06.png',
                        'img/endboss/Characters 05/Idle/Idle_07.png',
                        'img/endboss/Characters 05/Idle/Idle_08.png',
                        'img/endboss/Characters 05/Idle/Idle_09.png',
                        'img/endboss/Characters 05/Idle/Idle_10.png',
                        'img/endboss/Characters 05/Idle/Idle_11.png',
                        'img/endboss/Characters 05/Idle/Idle_12.png',
                        'img/endboss/Characters 05/Idle/Idle_13.png',
                        'img/endboss/Characters 05/Idle/Idle_14.png',
                        'img/endboss/Characters 05/Idle/Idle_15.png',
                        'img/endboss/Characters 05/Idle/Idle_16.png',
                        'img/endboss/Characters 05/Idle/Idle_17.png',
                        'img/endboss/Characters 05/Idle/Idle_18.png',
                        'img/endboss/Characters 05/Idle/Idle_19.png',
                    ],
                    
                    ENDBOSS_WALK: [
                        'img/endboss/Characters 05/Walk/Walk_00.png',
                        'img/endboss/Characters 05/Walk/Walk_01.png',
                        'img/endboss/Characters 05/Walk/Walk_02.png',
                        'img/endboss/Characters 05/Walk/Walk_03.png',
                        'img/endboss/Characters 05/Walk/Walk_04.png',
                        'img/endboss/Characters 05/Walk/Walk_05.png',
                        'img/endboss/Characters 05/Walk/Walk_06.png',
                        'img/endboss/Characters 05/Walk/Walk_07.png',
                        'img/endboss/Characters 05/Walk/Walk_08.png',
                        'img/endboss/Characters 05/Walk/Walk_09.png',
                        'img/endboss/Characters 05/Walk/Walk_10.png',
                        'img/endboss/Characters 05/Walk/Walk_11.png',
                        'img/endboss/Characters 05/Walk/Walk_12.png',
                        'img/endboss/Characters 05/Walk/Walk_13.png',
                        'img/endboss/Characters 05/Walk/Walk_14.png',
                        'img/endboss/Characters 05/Walk/Walk_15.png',
                        'img/endboss/Characters 05/Walk/Walk_16.png',
                        'img/endboss/Characters 05/Walk/Walk_17.png',
                        'img/endboss/Characters 05/Walk/Walk_18.png',
                        'img/endboss/Characters 05/Walk/Walk_19.png',
                    ],
                    
                    ENDBOSS_ATTACK: [
                        'img/endboss/Characters 05/Attack/Attack_00.png',
                        'img/endboss/Characters 05/Attack/Attack_01.png',
                        'img/endboss/Characters 05/Attack/Attack_02.png',
                        'img/endboss/Characters 05/Attack/Attack_03.png',
                        'img/endboss/Characters 05/Attack/Attack_04.png',
                        'img/endboss/Characters 05/Attack/Attack_05.png',
                        'img/endboss/Characters 05/Attack/Attack_06.png',
                        'img/endboss/Characters 05/Attack/Attack_07.png',
                        'img/endboss/Characters 05/Attack/Attack_08.png',
                        'img/endboss/Characters 05/Attack/Attack_09.png',
                        'img/endboss/Characters 05/Attack/Attack_10.png',
                        'img/endboss/Characters 05/Attack/Attack_11.png',
                        'img/endboss/Characters 05/Attack/Attack_12.png',
                        'img/endboss/Characters 05/Attack/Attack_13.png',
                        'img/endboss/Characters 05/Attack/Attack_14.png',
                        'img/endboss/Characters 05/Attack/Attack_15.png',
                        'img/endboss/Characters 05/Attack/Attack_16.png',
                        'img/endboss/Characters 05/Attack/Attack_17.png',
                        'img/endboss/Characters 05/Attack/Attack_18.png',
                        'img/endboss/Characters 05/Attack/Attack_19.png',
                        'img/endboss/Characters 05/Attack/Attack_20.png',
                        'img/endboss/Characters 05/Attack/Attack_21.png',
                        'img/endboss/Characters 05/Attack/Attack_22.png',
                        'img/endboss/Characters 05/Attack/Attack_23.png',
                        'img/endboss/Characters 05/Attack/Attack_24.png',
                    ],
                    
                    ENDBOSS_HURT: [
                        'img/endboss/Characters 05/Get Hit/Get Hit_00.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_01.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_02.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_03.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_04.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_05.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_06.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_07.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_08.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_09.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_10.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_11.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_12.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_13.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_14.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_15.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_16.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_17.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_18.png',
                        'img/endboss/Characters 05/Get Hit/Get Hit_19.png',
                    ],
                    
                    ENDBOSS_DEAD: [
                        'img/endboss/Characters 05/Death/Death_00.png',
                        'img/endboss/Characters 05/Death/Death_01.png',
                        'img/endboss/Characters 05/Death/Death_02.png',
                        'img/endboss/Characters 05/Death/Death_03.png',
                        'img/endboss/Characters 05/Death/Death_04.png',
                        'img/endboss/Characters 05/Death/Death_05.png',
                        'img/endboss/Characters 05/Death/Death_06.png',
                        'img/endboss/Characters 05/Death/Death_07.png',
                        'img/endboss/Characters 05/Death/Death_08.png',
                        'img/endboss/Characters 05/Death/Death_09.png',
                        'img/endboss/Characters 05/Death/Death_10.png',
                        'img/endboss/Characters 05/Death/Death_11.png',
                        'img/endboss/Characters 05/Death/Death_12.png',
                        'img/endboss/Characters 05/Death/Death_13.png',
                        'img/endboss/Characters 05/Death/Death_14.png',
                        'img/endboss/Characters 05/Death/Death_15.png',
                        'img/endboss/Characters 05/Death/Death_16.png',
                        'img/endboss/Characters 05/Death/Death_17.png',
                        'img/endboss/Characters 05/Death/Death_18.png',
                        'img/endboss/Characters 05/Death/Death_19.png',
                        'img/endboss/Characters 05/Death/Death_20.png',
                        'img/endboss/Characters 05/Death/Death_21.png',
                        'img/endboss/Characters 05/Death/Death_22.png',
                        'img/endboss/Characters 05/Death/Death_23.png',
                        'img/endboss/Characters 05/Death/Death_24.png',
                        'img/endboss/Characters 05/Death/Death_25.png',
                        'img/endboss/Characters 05/Death/Death_26.png',
                        'img/endboss/Characters 05/Death/Death_27.png',
                        'img/endboss/Characters 05/Death/Death_28.png',
                        'img/endboss/Characters 05/Death/Death_29.png',
                        'img/endboss/Characters 05/Death/Death_30.png',
                        'img/endboss/Characters 05/Death/Death_31.png',
                        'img/endboss/Characters 05/Death/Death_32.png',
                        'img/endboss/Characters 05/Death/Death_33.png',
                        'img/endboss/Characters 05/Death/Death_34.png',
                        'img/endboss/Characters 05/Death/Death_35.png',
                        'img/endboss/Characters 05/Death/Death_36.png',
                        'img/endboss/Characters 05/Death/Death_37.png',
                        'img/endboss/Characters 05/Death/Death_38.png',
                        'img/endboss/Characters 05/Death/Death_39.png',
                        'img/endboss/Characters 05/Death/Death_40.png',
                        'img/endboss/Characters 05/Death/Death_41.png',
                        'img/endboss/Characters 05/Death/Death_42.png',
                        'img/endboss/Characters 05/Death/Death_43.png',
                        'img/endboss/Characters 05/Death/Death_44.png',
                    ]
                    
                    }
                    }
                
            
        